### ISSUE TITLE
idf.py menuconfig报错：AttributeError: module 'kconfiglib' has no attribute 'BOOL'

### ISSUE THREAD

**Issue by hxgqh** [EnterTang/lvgl_rlottie_esp32#2]
报错内容：

```
Processing 1 dependencies:
[1/1] idf (4.4.6)
-- Project sdkconfig file /home/haomo/codes/github/lvgl_rlottie_esp32/sdkconfig
Traceback (most recent call last):
  File "/home/haomo/esp/esp-idf/tools/kconfig_new/confgen.py", line 644, in <module>
    main()
  File "/home/haomo/esp/esp-idf/tools/kconfig_new/confgen.py", line 330, in main
    output_function(deprecated_options, config, temp_file)
  File "/home/haomo/esp/esp-idf/tools/kconfig_new/confgen.py", line 407, in write_header
    deprecated_options.append_header(config, filename)
  File "/home/haomo/esp/esp-idf/tools/kconfig_new/confgen.py", line 186, in append_header
    if new_opt in config.syms and _opt_defined(config.syms[new_opt]):
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/haomo/esp/esp-idf/tools/kconfig_new/confgen.py", line 173, in _opt_defined
    if opt.orig_type in (kconfiglib.BOOL, kconfiglib.TRISTATE) and opt.str_value != 'n':
                         ^^^^^^^^^^^^^^^
AttributeError: module 'kconfiglib' has no attribute 'BOOL'
CMake Error at /home/haomo/esp/esp-idf/tools/cmake/kconfig.cmake:266 (message):
  Failed to run confgen.py
  (/home/haomo/.espressif/python_env/idf4.4_py3.11_env/bin/python;/home/haomo/esp/esp-idf/tools/kconfig_new/confgen.py;--kconfig;/home/haomo/esp/esp-idf/Kconfig;--sdkconfig-rename;/home/haomo/esp/esp-idf/sdkconfig.rename;--config;/home/haomo/codes/github/lvgl_rlottie_esp32/sdkconfig;--env-file;/home/haomo/codes/github/lvgl_rlottie_esp32/build/config.env).
  Error 1
Call Stack (most recent call first):
  /home/haomo/esp/esp-idf/tools/cmake/build.cmake:534 (__kconfig_generate_config)
  /home/haomo/esp/esp-idf/tools/cmake/project.cmake:476 (idf_build_process)
  CMakeLists.txt:6 (project)
```

**Comment by hxgqh** [comment]
已解决，参考：http://forum.esp32.com/viewtopic.php?t=41198
原因应该是在idf4.x和idf5.x之间反复切换导致。
解决办法：删除 ~/.espressif/python_env/idf4.x_py3.x_env，重新进入终端后运行 idf_tools.py install-python-env即可
